# Generated by Django 4.2.6 on 2023-10-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orden", "0004_alter_itemordendecompra_cantidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemordendecompra",
            name="precio_neto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
