# Generated by Django 4.2.6 on 2023-10-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orden", "0005_alter_itemordendecompra_precio_neto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemordendecompra",
            name="total_cargos",
        ),
        migrations.AddField(
            model_name="itemordendecompra",
            name="total_cargo",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
