# Generated by Django 4.2.6 on 2023-10-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orden", "0006_remove_itemordendecompra_total_cargos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemordendecompra",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="itemordendecompra",
            name="total_descuentos",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="itemordendecompra",
            name="total_impuestos",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
