# Generated by Django 4.2.6 on 2023-10-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orden", "0007_alter_itemordendecompra_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemordendecompra",
            name="moneda",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="itemordendecompra",
            name="unidad",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
